// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrG63l7h6B0N1bn0lDYMuFqVIl9qLv8Cw',
    appId: '1:997237652598:web:2be49bdbfff900c520f357',
    messagingSenderId: '997237652598',
    projectId: 'chat-app-dafeb',
    authDomain: 'chat-app-dafeb.firebaseapp.com',
    databaseURL: 'https://chat-app-dafeb-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-dafeb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGEsvS0xIGla4LZie4objU-6GNlixpyZY',
    appId: '1:997237652598:android:f0bcfc85c99db58520f357',
    messagingSenderId: '997237652598',
    projectId: 'chat-app-dafeb',
    storageBucket: 'chat-app-dafeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYJ1mOikgNZncbf8u9A_w8Ag93K4ZHHg8',
    appId: '1:997237652598:ios:84006b03cd96708220f357',
    messagingSenderId: '997237652598',
    projectId: 'chat-app-dafeb',
    storageBucket: 'chat-app-dafeb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYJ1mOikgNZncbf8u9A_w8Ag93K4ZHHg8',
    appId: '1:997237652598:ios:84006b03cd96708220f357',
    messagingSenderId: '997237652598',
    projectId: 'chat-app-dafeb',
    storageBucket: 'chat-app-dafeb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrG63l7h6B0N1bn0lDYMuFqVIl9qLv8Cw',
    appId: '1:997237652598:web:6ec04350f54faf9620f357',
    messagingSenderId: '997237652598',
    projectId: 'chat-app-dafeb',
    authDomain: 'chat-app-dafeb.firebaseapp.com',

    storageBucket: 'chat-app-dafeb.firebasestorage.app',
  );
}
